#!/bin/bash

XDG_CONFIG_DIR="${XDG_CONFIG_DIR:=$HOME/.config}"
CONFIG_DIR="${XDG_CONFIG_DIR}/i3blocks"
COLORS="${CONFIG_DIR}/colors"
[ -e "${COLORS}" ] && source "${COLORS}"

is_muted() {
  pactl get-sink-mute "${SINK}" \
    | awk '{ print $2 }'
}

volume() {
  pactl get-sink-volume "${SINK}" \
    | awk -F/ '{ gsub(/ /, ""); print $2 }'
}

SINK=${SINK:-@DEFAULT_SINK@}

if [ "no" == "$(is_muted)" ]; then
  volume
else
  echo "-"
  echo "-"
  if [ -n "${COLOR_WARNING}" ]; then
    echo "${COLOR_WARNING}"
  fi
fi
