return {
  "nvim-treesitter/nvim-treesitter",
  run = ":TSUpdate",
  config = function()
    require'nvim-treesitter.configs'.setup {
      ensure_installed = {
        "bash",
        "beancount",
        "c",
        "comment",
        "css",
        "dart",
        "dockerfile",
        "dot",
        "go",
        "gomod",
        "hcl",
        "html",
        "java",
        "javascript",
        "json",
        "kotlin",
        "ledger",
        "lua",
        "make",
        "php",
        "python",
        "regex",
        "ruby",
        "rust",
        "scss",
        "toml",
        "vim",
        "yaml",
        "zig",
      },
      highlight = { enable = true },
      indent = { enable = true },
    }
  end,
}
