#! /bin/bash

set -e

case $1 in
  aur)
    CMD=(paru --color=never -Qu)
    ;;

  *)
    CMD=(checkupdates --nocolor)
    ;;
esac

UPDATES=$("${CMD[@]}" | grep -vF '[ignored]' | sed 's/->//')
TEXT=""
TOOLTIP="Up to date"
CLASS=""

if [[ -n "${UPDATES}" ]]; then
  TEXT="$(printf "%s" "${UPDATES}" | grep -c '^')"
  TABLE=$(printf "Package Installed Available\n%s" "${UPDATES}" \
    | column -t \
    | sed '1,1s:Package:<b>Package</b>:' \
    | sed '1,1s:Installed:<b>Installed</b>:' \
    | sed '1,1s:Available:<b>Available</b>:'
  )
  TOOLTIP="<tt><small>${TABLE}</small></tt>"
  CLASS="pending"
fi

cat <<JSON
  {"text":"${TEXT}","tooltip":"${TOOLTIP//$'\n'/\\n}","class":"${CLASS}"}
JSON
