#!/bin/bash

# Apply theme colors.
#
# Basically pywal + functions to apply themes

set -e

XDG_CONFIG_DIR="${XDG_CONFIG_DIR:=$HOME/.config}"
XDG_CACHE_DIR="${XDG_CACHE_DIR:=$HOME/.cache}"
WAL_CACHE="${XDG_CACHE_DIR}/wal"

apply_oomox() {
  local theme
  theme=${WAL_CACHE}/colors-oomox

  command -v oomox-cli >/dev/null || return 1
  [ -e "${theme}" ] || return 1

  oomox-cli "${theme}" -o oomox-wal -t ~/.themes -m all
  gsettings set org.gnome.desktop.interface gtk-theme oomox-wal
  printf "%b\n" "[\e[1;32mI\e[0m] \e[1;31mpal\e[0m: Built oomox theme."
}

apply_terminal() {
  local theme
  theme=${WAL_CACHE}/colors-theme.sh

  # Pywal's built-in terminal handling isn't as robust as theme.sh's. In
  # particular theme.sh handles tmux better.
  command -v theme.sh >/dev/null || return 1
  [ -e "${theme}" ] || return 1

  theme.sh < "${theme}"
  printf "%b\n" "[\e[1;32mI\e[0m] \e[1;31mpal\e[0m: Applied terminal theme."
}

apply_swaylock() {
  local theme swaylock_config
  theme=${WAL_CACHE}/colors-swaylock
  swaylock_config=${XDG_CONFIG_DIR}/swaylock/config

  command -v swaylock >/dev/null || return 1
  [ -e "${theme}" ] || return 1
  [ -e "${swaylock_config}" ] && return 0 # don't overwrite config

  mkdir -p "${swaylock_config%/*}"
  ln -s "${theme}" "${swaylock_config}"
  printf "%b\n" "[\e[1;32mI\e[0m] \e[1;31mpal\e[0m: Linked swaylock config."
}

apply_mako() {
  systemctl --user is-active mako.service | grep '^active' > /dev/null || return 1

  systemctl --user restart mako.service
  printf "%b\n" "[\e[1;32mI\e[0m] \e[1;31mpal\e[0m: Restarted mako."
}

apply_swaybg() {
  systemctl --user is-active swaybg.service | grep '^active' > /dev/null || return 1

  systemctl --user restart swaybg.service
  printf "%b\n" "[\e[1;32mI\e[0m] \e[1;31mpal\e[0m: Restarted swaybg."
}

apply_waybar() {
  systemctl --user is-active waybar.service | grep '^active' > /dev/null || return 1

  systemctl --user restart waybar.service
  printf "%b\n" "[\e[1;32mI\e[0m] \e[1;31mpal\e[0m: Restarted waybar."
}

wal -st --theme default "$@"

apply_oomox &
apply_terminal &
apply_swaylock &
apply_mako &
apply_swaybg &
apply_waybar &
wait
